<Project>
  <PropertyGroup Label="Configure .csproj">
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>preview-all</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <AssemblyName>KappaDuck.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>

    <!-- Configure packages which are only Development dependency -->
    <!-- https://github.com/NuGet/Home/wiki/DevelopmentDependency-support-for-PackageReference -->
    <DevAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</DevAssets>
  </PropertyGroup>

  <PropertyGroup>
    <KhaosRoot>$(MSBuildThisFileDirectory)</KhaosRoot>
  </PropertyGroup>

  <ItemGroup Label="Configure analyzer rules">
    <GlobalAnalyzerConfigFiles Include="$(KhaosRoot)rules/*.editorconfig" />
  </ItemGroup>
</Project>
