<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <ItemGroup Label="Test packages">
    <PackageVersion Include="Basic.Reference.Assemblies.Net110" Version="1.8.12" />
    <PackageVersion Include="TUnit" Version="1.69.0" />
    <PackageVersion Include="TUnit.Mocks" Version="1.69.0" />
    <PackageVersion Include="TUnit.Mocks.Assertions" Version="1.69.0" />
    <PackageVersion Include="TUnit.Assertions.Should" Version="1.69.0-beta" />
    <PackageVersion Include="Verify.SourceGenerators" Version="2.5.0" />
    <PackageVersion Include="Verify.TUnit" Version="33.1.4" />
  </ItemGroup>
</Project>