// Copyright (c) KappaDuck.
// Licensed under the MIT license.

using KappaDuck.Khaos.Analyzers.Shared;

namespace KappaDuck.Khaos.Analyzers.Tests.Shared;

internal sealed class SourceBuilderTests
{
    [Test]
    public async Task BuilderShouldStartWithTheGeneratedHeader()
    {
        SourceBuilder builder = new();

        const string expected = """
            // <auto-generated/>
            #nullable enable

            """;

        await builder.Build().Should().BeEqualTo(expected.ReplaceLineEndings("\n"));
    }

    [Test]
    public async Task AppendLineShouldEmitLineFeeds()
    {
        SourceBuilder builder = new();

        builder.AppendLine("public sealed class Khaos;");
        await builder.Build().Should().NotContain("\r");
    }

    [Test]
    public async Task AppendLineShouldEmitLineFeedWhenThereIsNoParameter()
    {
        SourceBuilder builder = new();

        builder.AppendLine();

        const string expected = """
            // <auto-generated/>
            #nullable enable


            """;

        await builder.Build().Should().BeEqualTo(expected.ReplaceLineEndings("\n"));
    }

    [Test]
    public async Task AppendBlockShouldIndentUntilDisposed()
    {
        SourceBuilder builder = new();

        builder.AppendLine("namespace KappaDuck.Khaos.Windowing;")
               .AppendLine();

        using (builder.AppendBlock("public partial class Window"))
        {
            builder.AppendLine("public int Area => Width * Height;");
        }

        const string expected = """
            // <auto-generated/>
            #nullable enable
            namespace KappaDuck.Khaos.Windowing;

            public partial class Window
            {
                public int Area => Width * Height;
            }

            """;

        await builder.Build().Should().BeEqualTo(expected.ReplaceLineEndings("\n"));
    }

    [Test]
    public async Task AppendBlockWhenNestedShouldIndentEachLevel()
    {
        SourceBuilder builder = new();

        using (builder.AppendBlock("public partial class Window"))
        using (builder.AppendBlock("public void Show()"))
        {
            builder.AppendLine("throw new NotImplementedException();");
        }

        const string expected = """
            // <auto-generated/>
            #nullable enable
            public partial class Window
            {
                public void Show()
                {
                    throw new NotImplementedException();
                }
            }

            """;

        await builder.Build().Should().BeEqualTo(expected.ReplaceLineEndings("\n"));
    }

    [Test]
    public async Task AppendBlockShouldCloseWithTheGivenText()
    {
        SourceBuilder builder = new();

        using (builder.AppendBlock("public object? Value => _type switch", "};"))
        {
            builder.AppendLine("SDL_EventType.Quit => _quitRequested,")
                   .AppendLine("_ => null");
        }

        const string expected = """
            // <auto-generated/>
            #nullable enable
            public object? Value => _type switch
            {
                SDL_EventType.Quit => _quitRequested,
                _ => null
            };

            """;

        await builder.Build().Should().BeEqualTo(expected.ReplaceLineEndings("\n"));
    }
}
