// Copyright (c) KappaDuck.
// Licensed under the MIT license.

using System.Text;

namespace KappaDuck.Khaos.Analyzers.Shared;

internal sealed class SourceBuilder
{
    private const int IndentSize = 4;
    private const char NewLine = '\n';

    private readonly StringBuilder _builder = new();

    private int _indentation;

    internal SourceBuilder()
    {
        AppendLine("// <auto-generated/>");
        AppendLine("#nullable enable");
    }

    internal Block AppendBlock(string line) => AppendBlock(line, "}");

    internal Block AppendBlock(string line, string closing)
    {
        AppendLine(line);
        AppendLine("{");

        _indentation++;

        return new Block(this, closing);
    }

    internal SourceBuilder AppendLine(string line)
    {
        if (line.Length > 0)
            _builder.Append(' ', _indentation * IndentSize);

        _builder.Append(line).Append(NewLine);
        return this;
    }

    internal SourceBuilder AppendLine()
    {
        _builder.Append(NewLine);
        return this;
    }

    internal string Build() => _builder.ToString();

    private void Close(string closing)
    {
        _indentation--;
        AppendLine(closing);
    }

    internal readonly struct Block(SourceBuilder builder, string closing) : IDisposable
    {
        public void Dispose() => builder.Close(closing);
    }
}
